import React, { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Typography, Grid, Box, Button } from '@mui/material';
import { red } from '@mui/material/colors';
// import backgroundVideo01 from '../public/videos/video01.mp4';

export default function Home() {
	const movieArray = [
		'https://vod-progressive.akamaized.net/exp=1659828360~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F1248%2F16%2F406244757%2F1740110380.mp4~hmac=788e966f609e230de5a77d6eb678f2d80ef87bdada03652edfb7cb0ac63a7947/vimeo-prod-skyfire-std-us/01/1248/16/406244757/1740110380.mp4',
		'https://vod-progressive.akamaized.net/exp=1659823997~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F376%2F18%2F451884027%2F1988225016.mp4~hmac=af451bc96cc0d725416fced41025c289d7d8738a240a993724d89e042d328c3f/vimeo-prod-skyfire-std-us/01/376/18/451884027/1988225016.mp4',
		'https://vod-progressive.akamaized.net/exp=1659824152~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F486%2F26%2F652433269%2F2994448325.mp4~hmac=32fb95b6f3f315feb3a83feeed27a9377630630825401ea43d48c534899f0024/vimeo-prod-skyfire-std-us/01/486/26/652433269/2994448325.mp4',
		'https://vod-progressive.akamaized.net/exp=1659824279~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F78%2F24%2F600391153%2F2819399062.mp4~hmac=d13c3b021d716025fde4e1c2c79397030fcbc2b26b11a1a67b8f77fee80c4f52/vimeo-prod-skyfire-std-us/01/78/24/600391153/2819399062.mp4',
		'https://vod-progressive.akamaized.net/exp=1659824332~acl=%2Fvimeo-prod-skyfire-std-us%2F01%2F1484%2F20%2F507421043%2F2330673558.mp4~hmac=9364a94bd16767b59729f03e6467a500bd97a1b30d7f448a0844ea272d948ca3/vimeo-prod-skyfire-std-us/01/1484/20/507421043/2330673558.mp4',
	];
	const [index, setIndex] = useState(0);
	const [movieState, setMovieState] = useState(movieArray[0]);
	const currentMovie = movieArray[index];
	const movieIndex = setInterval(movieCallback, 7000);

	function movieCallback() {
		if (index == movieArray.length - 1) {
			setIndex(0);
			// setMovieState(movieArray[0]);
		} else {
			setIndex(index + 1);
			// setMovieState(movieArray[index + 1]);
		}
	}

	return (
		<div>
			<Head>
				<title>Fair Oak Farms Rental Application</title>
				{/* <meta name='description' content='Generated by create next app' /> */}
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Box id='videoContainer'>
					{/* <video autoPlay loop muted className='video'> */}
					{/* LEAVING THESE LINES TO TO DETERMINE WHY THEY DIDN'T CHANGE BACKGROUND
					AS INTENDED WHEN PART OF ABOVE VIDEO ELEMENT */}
					{/* <source src={currentMovie} type='video/mp4' /> */}
					{/* <source src={movieState} type='video/mp4' /> */}
					{/* <source src={movieArray[movieIndex]} type='video/mp4' /> */}
					{/* <source src={movieArray[index]} type='video/mp4' /> */}
					{index == 0 && (
						<video autoPlay loop muted className='video'>
							<source src={movieArray[index]} type='video/mp4' />
						</video>
					)}
					{index == 1 && (
						<video autoPlay loop muted className='video'>
							<source src={movieArray[index]} type='video/mp4' />
						</video>
					)}
					{index == 2 && (
						<video autoPlay loop muted className='video'>
							<source src={movieArray[index]} type='video/mp4' />
						</video>
					)}
					{index == 3 && (
						<video autoPlay loop muted className='video'>
							<source src={movieArray[index]} type='video/mp4' />
						</video>
					)}
					{index == 4 && (
						<video autoPlay loop muted className='video'>
							<source src={movieArray[index]} type='video/mp4' />
						</video>
					)}
					{/* </video> */}
				</Box>
				<Box
					sx={{
						flexGrow: 1,
					}}
					id='homePageContainer'
				>
					<Grid container spacing={2}>
						<Grid item xs={12} md={12}>
							<Typography variant='h2' align='center' className='heroText'>
								Welcome to the Fair Oak Farms Rental Application!
							</Typography>
						</Grid>
						<Grid item xs={12} md={12}>
							<Typography variant='h4' align='center' className='heroText'>
								Please click below if you would like to apply for one of our
								properties!
							</Typography>
						</Grid>
						<Link href='/rentalApplication'>
							<Grid item xs={12} md={12} id='applyButtonContainer'>
								<Button variant='contained'>Apply Here!</Button>
							</Grid>
						</Link>
					</Grid>
				</Box>
			</main>

			{/* <footer>
				<Typography variant='subtitle2'>
					Created by{' '}
					<strong>
						<i>BX Development</i>
					</strong>
				</Typography>
			</footer> */}
		</div>
	);
}
